### ISSUE TITLE
你这个库是用来在android webview上进行scatter注入的吗？

### ISSUE THREAD

**Issue by plaichat1986** [xuewuli/Tiny.Scatter#1]

**Comment by xuewuli** [comment]
可以用来干这个事情，但这里只是要注入的代码本身，不包括WebView实现注入的部分
另外这个是刚刚实现的仅测试过个位数的DAPP，仅供学习参考

**Comment by plaichat1986** [comment]
> 可以用来干这个事情，但这里只是要注入的代码本身，不包括WebView实现注入的部分
> 另外这个是刚刚实现的仅测试过个位数的DAPP，仅供学习参考

好的，谢谢
