### ISSUE TITLE
iOS想使用, 能说下XMethod这个枚举的类型么？

### ISSUE THREAD

**Issue by HelloHchen** [xuewuli/Tiny.Scatter#10]
XMethod
![image](https://user-images.githubusercontent.com/38774301/63077207-1a49e600-bf6a-11e9-9f7b-8e437de69d3e.png)

**Comment by xuewuli** [comment]
String, 相当于字符串“signEOS"
参看WKUserContentController的说明
https://developer.apple.com/documentation/webkit/wkusercontentcontroller/1537172-add

**Comment by HelloHchen** [comment]
其实我是想知道你的 enum 中 case signEOS字符串值是什么 
enum Xmethod: String {
case signEOS = "signEOS"
...
}
？

**Comment by HelloHchen** [comment]
你是支持最新版scatter了么？ 前端开发说新版代码是socket 连接，移动端代码有什么相应的更改么？
之前是借用https://github.com/ProChain/pra_scatter_middleware这位作者的

**Comment by xuewuli** [comment]
1、对的，就是“signEOS”
2、和pra_scatter效果是一样的，如果已经接入了倒是也没必要换
3、scatter用socket应该是指scatter钱包的桌面版吧

**Comment by HelloHchen** [comment]
具体不是清楚，前端说scatter登录方法从getIdentity=>login

**Comment by xuewuli** [comment]
是新增了方法吗？那这边还没有跟着升级。最近事多，过些日子看看。欢迎PR。
