### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by sfsw** [xuewuli/Tiny.Scatter#3]
undefined is not an object (evaluating 'window.webkit.messageHandles')
现在包这个错，另外问下示例中：XMethod.signEOS.rawValue，这个具体要实现什么？

**Comment by xuewuli** [comment]
因为这个是iOS的webview提供的，在Android上你需要替换这部分代码，或在注入初始化的地方自己模拟这个接口

**Comment by xuewuli** [comment]
XMethod.singEOS是我实现iOS版应用时定义的enum，和这个库没有关系

**Comment by sfsw** [comment]
现在已经signEOS已经调用成功了，能取回json数据，之后在如何操作？

**Comment by xuewuli** [comment]
拿去签名，返回签名结果，结果的格式参考readme

**Comment by Mubly** [comment]
Android也报这个错，该怎么弄？模拟什么接口？或者再注入什么方法？

**Comment by Mubly** [comment]
Cannot read property ‘messageHandlers’ of undefined 这个要怎么解决？

**Comment by xuewuli** [comment]
> Cannot read property ‘messageHandlers’ of undefined 这个要怎么解决？

你和楼主问的是一个问题
因为window.webkit这个是iOS的webview提供的，在Android上你需要替换这部分代码，或在注入初始化的地方自己模拟这个接口

这个仓库是学习用的,作为需要实现兼容scatter的参考,不建议直接使用

**Comment by xuewuli** [comment]
我在readme中增加了一部分说明,希望有所帮助.

**Comment by Mubly** [comment]
好吧。Thankyou

**Comment by sfsw** [comment]
怎么去拿签名，具体是调用什么？

**Comment by xuewuli** [comment]
> 怎么去拿签名，具体是调用什么？

签名是“钱包”部分的功能
注入的作用是把webview中网页发起的签名请求传递给原生,这样钱包就可以进行签名,签完再通过webview传递回去. 所以如何完成签名是要看你用什么代码实现的“钱包”

**Comment by sfsw** [comment]
> > 怎么去拿签名，具体是调用什么？
> 
> 签名是“钱包”部分的功能,注入的作用是把webview中网页发起的签名请求传递给原生,这样钱包就可以进行签名,签完再通过webview传递回去.
> 所以如何完成签名是要看你用什么代码实现的“钱包”
> 当有了签名结果,就可以通过webview.evaluateJavascript调用onSignEOSSuccessful,回传给网页
> 
> 另外readme也稍稍更新了一下,对onSignEOSSuccessful有一定的说明

了解了，正常尝试签名

**Comment by sfsw** [comment]
Printing description of error:
Error Domain=WKErrorDomain Code=4 "发生 JavaScript 异常" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=SyntaxError: Unexpected EOF, WKJavaScriptExceptionColumnNumber=0, WKJavaScriptExceptionSourceURL=https://betdice.one/?ref=gy4tqnbvg4ge, NSLocalizedDescription=发生 JavaScript 异常}

签名完成后开始调用onSignEOSSuccessful，报错如上

**Comment by sfsw** [comment]
大神，能不能加个微信交流，感觉我快成功了，微信号：sfswow
@xuewuli
