### ISSUE TITLE
关于XWebView

### ISSUE THREAD

**Issue by Mubly** [xuewuli/Tiny.Scatter#4]
XWebView是  webView.addJavascriptInterface(new JSApi (), "XWebView");里面的“XWebView”吗？

**Comment by Mubly** [comment]
我这边已经明白了，不过Android注入的时候messageHandlers 生成后面要加上“；”不然会注入失败的。希望底下用到的人能够知道

**Comment by sfsw** [comment]
我们Andoroid遇到了，多谢楼主！

**Comment by 29745560** [comment]
> 我们Andoroid遇到了，多谢楼主！

能否留个联系方式？谢谢

**Comment by 29745560** [comment]
> 我这边已经明白了，不过Android注入的时候messageHandlers 生成后面要加上“；”不然会注入失败的。希望底下用到的人能够知道

能否留个联系方式？谢谢

**Comment by sfsw** [comment]
微信 sfswow
