### ISSUE TITLE
关于如何处理 scatter 的 sign arbitrary

### ISSUE THREAD

**Issue by xuewuli** [xuewuli/Tiny.Scatter#5]
# 收到的数据
````js
{
"publicKey":"xxxxxx",
"data":"yyyyyyy",
"whatfor":"wwwww",
"isHash":false
}
````
publicKey 用于找到对应的私钥,若是注入webview应该可以假定就是当前账户
data 需要签名的数据
whatfor UI显示用
isHash 决定签名方式
* true 使用 ecc.Signature.signHash
* false 使用 ecc.sign
# 返回数据
只需要将签名结果返回, 不是对象也不是数组,就是只 "SIG_K1_..." 这样一个字符串
* BrigeAPI.sendResponse(1111111, "SIG_K1_...")

**Comment by HallCheng** [comment]
> # 收到的数据
> ```js
> {
> "publicKey":"xxxxxx",
> "data":"yyyyyyy",
> "whatfor":"wwwww",
> "isHash":false
> }
> ```
> 
> publicKey 用于找到对应的私钥,若是注入webview应该可以假定就是当前账户
> data 需要签名的数据
> whatfor UI显示用
> isHash 决定签名方式
> 
> * true 使用 ecc.Signature.signHash
> * false 使用 ecc.sign
> 
> # 返回数据
> 只需要将签名结果返回, 不是对象也不是数组,就是只 "SIG_K1_..." 这样一个字符串
> 
> * BrigeAPI.sendResponse(1111111, "SIG_K1_...")

当 isHash 为True时，data 中的数据是 sha25数据吗？还没有遇到过这种授权。

**Comment by HallCheng** [comment]
> # 收到的数据
> ```js
> {
> "publicKey":"xxxxxx",
> "data":"yyyyyyy",
> "whatfor":"wwwww",
> "isHash":false
> }
> ```
> 
> publicKey 用于找到对应的私钥,若是注入webview应该可以假定就是当前账户
> data 需要签名的数据
> whatfor UI显示用
> isHash 决定签名方式
> 
> * true 使用 ecc.Signature.signHash
> * false 使用 ecc.sign
> 
> # 返回数据
> 只需要将签名结果返回, 不是对象也不是数组,就是只 "SIG_K1_..." 这样一个字符串
> 
> * BrigeAPI.sendResponse(1111111, "SIG_K1_...")

当 isHash 为True时，data 中的数据是 sha256数据吗？还没有遇到过这种授权。

**Comment by xuewuli** [comment]
是的,这里是参考scatter desktop的实现些的说明. isHash的我也没遇到过,用sign arbitrary本就不多
