### ISSUE TITLE
由H5开发的钱包能够实现scatter 注入不

### ISSUE THREAD

**Issue by AIYP1226** [xuewuli/Tiny.Scatter#7]
您好，我们的钱包是纯H5开发的，请教下这种情况怎么实现scatter注入啊

**Comment by xuewuli** [comment]
纯H5不是很了解,理论上只要让dapp认为window.scatter有已经初始化好的scatter对象就可以.

**Comment by cjz9032** [comment]
> 纯H5不是很了解,理论上只要让dapp认为window.scatter有已经初始化好的scatter对象就可以.

不是的吧，纯h5不太可能实现的，他本质上是钱包这一层存储了相关私钥，然后钱包用ws本地通信给该dapp。纯h5么，想象不到怎么做
